### ISSUE TITLE
Is this meant to run as is?

### ISSUE THREAD

**Issue by sturgman** [mbutterick/pollen-tfl#4]
Hello! I am trying to learn pollen and I was using this repository to explore things. I tried two methods: installing it via raco and by just cloning the repository. In both instances, I had trouble rendering any of the files due to an error related to Equity URL not being found.

So my question is: am I supposed to be able to render this repository in my computer? My guess is yes since the readme mentions it is an aid for learning pollen.

Perhaps it would be wise to remove the Equity (and any other MB) font dependence?

This is the exact error message:

```
Exception

The application raised an exception with the message:

no URL found for "Equity"

Stack trace:

```
I have since tried to remove Equity from the project, but I failed at this. Let me know if there is something I can do to help.

**Comment by sturgman** [comment]
Since posting this, I note that the page `why-typography-matters.html.pm` does not render because of the Equity error above, but the page `type-composition.html.pm` renders with lower quality fonts 😆 I looked at the code for both of those but it is not clear to me why one works and the other doesn't. Since I have some pages that work, this is probably sufficient for me to play around with. Definitely something to consider if reproducible though.

**Comment by mbutterick** [comment]
I broke some things recently; I’ve now patched them. It works again (for me). 

(Eventually I’d like to replace this with a new tutorial project. It’s not likely to happen for at least 6 months. Still, this sample project shows all the principal techniques, which is the point.)

**Comment by sturgman** [comment]
Thank you for the ultra-fast response.... everything seems to be working now.
